[package]
name = "osquery_readable"
version = "0.1.0"
authors = ["zouxiaoliang <295919168@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.16.0"
clap = "3.0.0-beta.2"
